[vicis_ir] Implement parse_metadata in module
maekawatoshiki/vicis pull request #3
Opened 2021-08-01 12:32 UTC by hsk

rustfmt を通して、型情報を付加し、module.metas にパース結果を保存し fmt::Debug にも対応しました。

2021-08-01 12:54 UTC, maekawatoshiki requested changes
ありがとうございます。いくつかコメントを追加しておきました。あと、PRは毎度作り直さなくても、`hsk:master`へプッシュすれば自動的に更新されると思います。

2021-08-01 12:54 UTC, maekawatoshiki commented on vicis_ir/src/ir/module/parser.rs
> +impl Module {
`Module`にパース用の関数を実装する必要はあるでしょうか。(パースの関数は`Module`のimplから分離したいです)。もし`Module.types`がパース時に必要なのであれば、`Module.types`のみをクロージャに渡してやれば良いと思います。(詳しくは130行目へ)

2021-08-01 12:54 UTC, maekawatoshiki commented on vicis_ir/src/ir/module/parser.rs
>  }
```rs
fn parse_metadata(types: &types::Types) -> 
        impl FnMut(&str) -> IResult<&str, Vec<(Name, Meta)>, VerboseError<&str>> {
    // source: &str を受け取るクロージャを返す
}
```
のように変更してはいかがでしょうか。パース時に必要なのは`Module`全体ではなく、型データ`Types`のみだと思います。

2021-08-01 13:25 UTC, maekawatoshiki requested changes

2021-08-01 13:25 UTC, maekawatoshiki commented on vicis_ir/src/ir/module/parser.rs
> +        assert!(process::Command::new("llc")
`llc-12`に戻していただけないでしょうか。CIが落ちてしまって... (あとで`llc`でも動くようにしておきます)

2021-08-01 16:53 UTC, hsk commented on vicis_ir/src/ir/module/parser.rs
>  }
変更しました。 + '_ をつけないといけないところでだいぶ悩んでしまいました。

2021-08-01 16:54 UTC, hsk commented on vicis_ir/src/ir/module/parser.rs
> +        assert!(process::Command::new("llc")
llc-12 が動かないので、llcにして戻してとやってたのですけど戻し漏れていたようです。

2021-08-02 09:54 UTC, maekawatoshiki commented
LGTM. ありがとうございます。

2021-08-02 09:54 UTC, merged